import type { TemplateVersionVariable } from '@/lib/templates';

export type TemplatePreset = {
  code: string;
  name_ar: string;
  category: string;
  variables: TemplateVersionVariable[];
};

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    code: 'WAKALA',
    name_ar: 'وكالة (أساسي)',
    category: 'وكالة',
    variables: [
      {
        key: 'org.name',
        label_ar: 'اسم المكتب',
        required: false,
        source: 'org',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: 'اسم المكتب كما هو مسجل في المنصة.',
      },
      {
        key: 'date.today',
        label_ar: 'تاريخ اليوم (ميلادي)',
        required: false,
        source: 'computed',
        path: '',
        format: 'date',
        transform: 'none',
        defaultValue: '',
        help_ar: 'تاريخ اليوم بصيغة عربية.',
      },
      {
        key: 'date.hijri_today',
        label_ar: 'تاريخ اليوم (هجري)',
        required: false,
        source: 'computed',
        path: '',
        format: 'date',
        transform: 'none',
        defaultValue: '',
        help_ar: 'تاريخ اليوم بالتقويم الهجري (إن توفر).',
      },
      {
        key: 'client.name',
        label_ar: 'اسم الموكل',
        required: true,
        source: 'client',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: 'يظهر في مقدمة المستند.',
      },
      {
        key: 'client.identity_no',
        label_ar: 'رقم الهوية',
        required: false,
        source: 'client',
        path: 'identity_no',
        format: 'id',
        transform: 'none',
        defaultValue: '',
        help_ar: 'رقم الهوية الوطنية/الإقامة.',
      },
      {
        key: 'manual.agent_name',
        label_ar: 'اسم الوكيل',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: 'اسم الوكيل المراد تفويضه.',
      },
      {
        key: 'manual.subject',
        label_ar: 'موضوع الوكالة',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: 'موضوع الوكالة ونطاقها.',
      },
    ],
  },
  {
    code: 'PETITION',
    name_ar: 'لائحة دعوى (مختصر)',
    category: 'لائحة دعوى',
    variables: [
      {
        key: 'org.name',
        label_ar: 'اسم المكتب',
        required: false,
        source: 'org',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'client.name',
        label_ar: 'اسم المدعي',
        required: true,
        source: 'client',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'matter.title',
        label_ar: 'عنوان الدعوى',
        required: true,
        source: 'matter',
        path: 'title',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'matter.summary',
        label_ar: 'ملخص الدعوى',
        required: false,
        source: 'matter',
        path: 'summary',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.claim_amount',
        label_ar: 'مبلغ المطالبة',
        required: true,
        source: 'manual',
        path: '',
        format: 'number',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.requests',
        label_ar: 'الطلبات',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: 'اكتب الطلبات بشكل نقاط.',
      },
    ],
  },
  {
    code: 'MEMO',
    name_ar: 'مذكرة (عام)',
    category: 'مذكرة',
    variables: [
      {
        key: 'client.name',
        label_ar: 'اسم الموكل',
        required: false,
        source: 'client',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'matter.title',
        label_ar: 'عنوان القضية',
        required: false,
        source: 'matter',
        path: 'title',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.subject',
        label_ar: 'موضوع المذكرة',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.body',
        label_ar: 'نص المذكرة',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
    ],
  },
  {
    code: 'NOTICE',
    name_ar: 'إنذار (أساسي)',
    category: 'إنذار',
    variables: [
      {
        key: 'client.name',
        label_ar: 'اسم المرسل',
        required: true,
        source: 'client',
        path: 'name',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.recipient_name',
        label_ar: 'اسم المستلم',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.subject',
        label_ar: 'موضوع الإنذار',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
      {
        key: 'manual.body',
        label_ar: 'نص الإنذار',
        required: true,
        source: 'manual',
        path: '',
        format: 'text',
        transform: 'none',
        defaultValue: '',
        help_ar: '',
      },
    ],
  },
];
