import type { JsonObject, JsonValue } from '../../domain/models';

export type NajizApiError = {
  code?: string | number;
  message?: string;
  details?: string;
  [key: string]: unknown;
};

export type NajizApiEnvelope<T extends Record<string, unknown> = JsonObject> = {
  data?: T | T[];
  items?: T[];
  results?: T[];
  cases?: T[];
  costs?: T[];
  requests?: T[];
  documents?: T[];
  session_minutes?: T[];
  minutes?: T[];
  enforcement_requests?: T[];
  hearings?: T[];
  errors?: NajizApiError[];
  message?: string;
  status?: string;
  [key: string]: JsonValue | T | T[] | NajizApiError[] | undefined;
};

export type NajizLawyerVerificationPayload = {
  id?: string | number;
  lawyerId?: string | number;
  external_id?: string | number;
  licenseNumber?: string;
  license_number?: string;
  nationalId?: string;
  national_id?: string;
  name?: string;
  fullName?: string;
  lawyer_name?: string;
  officeName?: string;
  office_name?: string;
  status?: string;
  verificationStatus?: string;
  verifiedAt?: string;
  verified_at?: string;
  expiresAt?: string;
  expires_at?: string;
  [key: string]: unknown;
};

export type NajizPowerOfAttorneyPayload = {
  id?: string | number;
  external_id?: string | number;
  poaId?: string | number;
  poa_id?: string | number;
  poaNumber?: string;
  poa_number?: string;
  clientId?: string | number;
  client_id?: string | number;
  holderName?: string;
  holder_name?: string;
  status?: string;
  isRevoked?: boolean;
  is_revoked?: boolean;
  revoked?: boolean;
  issuedAt?: string;
  issued_at?: string;
  expiresAt?: string;
  expires_at?: string;
  verifiedAt?: string;
  verified_at?: string;
  [key: string]: unknown;
};

export type NajizCasePayload = {
  id?: string | number;
  external_id?: string | number;
  caseId?: string | number;
  case_id?: string | number;
  caseNumber?: string | number;
  case_number?: string | number;
  reference?: string | number;
  title?: string;
  caseTitle?: string;
  case_title?: string;
  subject?: string;
  court?: string;
  court_name?: string;
  courtName?: string;
  status?: string;
  case_status?: string;
  caseStatus?: string;
  events?: NajizCaseEventPayload[];
  hearings?: NajizCaseEventPayload[];
  activities?: NajizCaseEventPayload[];
  [key: string]: unknown;
};

export type NajizCaseEventPayload = {
  id?: string | number;
  external_id?: string | number;
  eventId?: string | number;
  event_id?: string | number;
  type?: string;
  eventType?: string;
  event_type?: string;
  title?: string;
  label?: string;
  description?: string;
  note?: string;
  occurredAt?: string;
  occurred_at?: string;
  date?: string;
  sessionDate?: string;
  session_date?: string;
  [key: string]: unknown;
};

export type NajizJudicialCostPayload = {
  id?: string | number;
  external_id?: string | number;
  caseId?: string | number;
  case_id?: string | number;
  caseNumber?: string | number;
  case_number?: string | number;
  type?: string;
  costType?: string;
  cost_type?: string;
  title?: string;
  description?: string;
  amount?: string | number;
  total?: string | number;
  currency?: string;
  status?: string;
  invoiceReference?: string;
  invoice_reference?: string;
  dueAt?: string;
  due_at?: string;
  [key: string]: unknown;
};

export type NajizEnforcementRequestPayload = {
  id?: string | number;
  external_id?: string | number;
  requestId?: string | number;
  request_id?: string | number;
  requestNumber?: string | number;
  request_number?: string | number;
  type?: string;
  requestType?: string;
  request_type?: string;
  caseId?: string | number;
  case_id?: string | number;
  caseNumber?: string | number;
  case_number?: string | number;
  title?: string;
  subject?: string;
  status?: string;
  applicantName?: string;
  applicant_name?: string;
  respondentName?: string;
  respondent_name?: string;
  amount?: string | number;
  currency?: string;
  submittedAt?: string;
  submitted_at?: string;
  closedAt?: string;
  closed_at?: string;
  events?: NajizEnforcementRequestEventPayload[];
  actions?: NajizEnforcementRequestEventPayload[];
  timeline?: NajizEnforcementRequestEventPayload[];
  activities?: NajizEnforcementRequestEventPayload[];
  [key: string]: unknown;
};

export type NajizEnforcementRequestEventPayload = {
  id?: string | number;
  external_id?: string | number;
  eventId?: string | number;
  event_id?: string | number;
  actionType?: string;
  action_type?: string;
  type?: string;
  title?: string;
  label?: string;
  description?: string;
  note?: string;
  occurredAt?: string;
  occurred_at?: string;
  date?: string;
  [key: string]: unknown;
};

export type NajizDocumentPayload = {
  id?: string | number;
  external_id?: string | number;
  documentId?: string | number;
  document_id?: string | number;
  caseId?: string | number;
  case_id?: string | number;
  caseNumber?: string | number;
  case_number?: string | number;
  type?: string;
  documentType?: string;
  document_type?: string;
  title?: string;
  subject?: string;
  fileName?: string;
  file_name?: string;
  mimeType?: string;
  mime_type?: string;
  downloadUrl?: string;
  download_url?: string;
  fileSize?: string | number;
  file_size?: string | number;
  checksum?: string;
  sha256?: string;
  issuedAt?: string;
  issued_at?: string;
  portalVisible?: boolean;
  portal_visible?: boolean;
  [key: string]: unknown;
};

export type NajizSessionMinutePayload = {
  id?: string | number;
  external_id?: string | number;
  minuteId?: string | number;
  minute_id?: string | number;
  caseId?: string | number;
  case_id?: string | number;
  caseNumber?: string | number;
  case_number?: string | number;
  sessionReference?: string;
  session_reference?: string;
  title?: string;
  summary?: string;
  note?: string;
  occurredAt?: string;
  occurred_at?: string;
  date?: string;
  documentId?: string | number;
  document_id?: string | number;
  minuteDocumentId?: string | number;
  minute_document_id?: string | number;
  [key: string]: unknown;
};
